In [43]:
import pandas as pd
import numpy as np
df=pd.read_csv('pandas_exam_data_v2.csv')
df

   员工编号       姓名    年龄  工龄      工资  部门
0  1001    Alice  28.0   3  7000.0  销售
1  1002      Bob  34.0   8  8800.0  技术
2  1003  Charlie  29.0   5  7300.0  技术
3  1004    David  41.0  10  9600.0  人事
4  1005      Eva  25.0   2     NaN  销售
5  1006      Bob  34.0   8  8800.0  技术
6  1007      NaN   NaN   4  7600.0  行政

In [44]:
df=df.fillna({"工资": df["工资"].median()})
df

   员工编号       姓名    年龄  工龄      工资  部门
0  1001    Alice  28.0   3  7000.0  销售
1  1002      Bob  34.0   8  8800.0  技术
2  1003  Charlie  29.0   5  7300.0  技术
3  1004    David  41.0  10  9600.0  人事
4  1005      Eva  25.0   2  8200.0  销售
5  1006      Bob  34.0   8  8800.0  技术
6  1007      NaN   NaN   4  7600.0  行政

In [45]:
df = df.drop_duplicates(subset=["姓名"]) 
df

   员工编号       姓名    年龄  工龄      工资  部门
0  1001    Alice  28.0   3  7000.0  销售
1  1002      Bob  34.0   8  8800.0  技术
2  1003  Charlie  29.0   5  7300.0  技术
3  1004    David  41.0  10  9600.0  人事
4  1005      Eva  25.0   2  8200.0  销售
6  1007      NaN   NaN   4  7600.0  行政

In [46]:
df=df.drop(columns=['姓名'])
df

   员工编号    年龄  工龄      工资  部门
0  1001  28.0   3  7000.0  销售
1  1002  34.0   8  8800.0  技术
2  1003  29.0   5  7300.0  技术
3  1004  41.0  10  9600.0  人事
4  1005  25.0   2  8200.0  销售
6  1007   NaN   4  7600.0  行政

In [16]:
df['工龄']=df['工龄'].astype(float)
df

   员工编号    年龄    工龄           工资  部门
0  1001  28.0   3.0  7000.000000  销售
1  1002  34.0   8.0  8800.000000  技术
2  1003  29.0   5.0  7300.000000  技术
3  1004  41.0  10.0  9600.000000  人事
4  1005  25.0   2.0  8183.333333  销售
6  1007   NaN   4.0  7600.000000  行政

In [21]:
dsum=df['工资'].sum()
mean=df['工资'].mean()
std = df['工资'].std()

print(dsum,
mean,
std)

48483.333333333336 8080.555555555556 984.3450539242757

In [22]:
opgroup= df.groupby("部门").agg(平均工资=('工资','mean') ,平均年龄=('年龄','mean'))
opgroup

           平均工资  平均年龄
部门
人事  9600.000000  41.0
技术  8050.000000  31.5
行政  7600.000000   NaN
销售  7591.666667  26.5

In [25]:
df['年龄段']=pd.cut(df['年龄'],bins=[0,30,40,60],labels=["青年", "中年", "中老年"])
df

   员工编号    年龄    工龄           工资  部门  年龄段
0  1001  28.0   3.0  7000.000000  销售   青年
1  1002  34.0   8.0  8800.000000  技术   中年
2  1003  29.0   5.0  7300.000000  技术   青年
3  1004  41.0  10.0  9600.000000  人事  中老年
4  1005  25.0   2.0  8183.333333  销售   青年
6  1007   NaN   4.0  7600.000000  行政  NaN

In [27]:
df.value_counts("部门")

部门
销售    2
技术    2
人事    1
行政    1
Name: count, dtype: int64

In [33]:
df['薪级别']=np.where(df['工资'] > 8000,"高新","普通")
df

   员工编号    年龄    工龄           工资  部门  年龄段 薪级别
0  1001  28.0   3.0  7000.000000  销售   青年  普通
1  1002  34.0   8.0  8800.000000  技术   中年  高新
2  1003  29.0   5.0  7300.000000  技术   青年  普通
3  1004  41.0  10.0  9600.000000  人事  中老年  高新
4  1005  25.0   2.0  8183.333333  销售   青年  高新
6  1007   NaN   4.0  7600.000000  行政  NaN  普通

In [35]:
df[df['年龄'].between(30,40)]

   员工编号    年龄   工龄      工资  部门 年龄段 薪级别
1  1002  34.0  8.0  8800.0  技术  中年  高新

In [40]:
len(df['员工编号'])

6

In [41]:
df.to_csv("processed_data_v2.csv", index=False)