In [69]:
import pandas as pd
# df=pd.read_csv('pandas_exam_data.csv').head()
df=pd.read_csv('pandas_exam_data.csv')

In [77]:
pd.isnull(df)
df.dropna()

   姓名  年龄      工资  部门
0  张三  23  5000.0  财务
1  李四  45  8000.0  技术
2  王五  31  6200.0  技术
3  赵六  23  7100.0  人事

In [78]:
df.fillna({"工资": df["工资"].mean()})

    姓名  年龄      工资  部门
0   张三  23  5000.0  财务
1   李四  45  8000.0  技术
2   王五  31  6200.0  技术
3   赵六  23  7100.0  人事
4   钱七  22  6600.0  财务
6  NaN  30  6700.0  人事

In [79]:
# df['是否重复'] = df.duplicated(keep=False)
df = df.drop_duplicates(subset=["姓名"])
df

    姓名  年龄      工资  部门
0   张三  23  5000.0  财务
1   李四  45  8000.0  技术
2   王五  31  6200.0  技术
3   赵六  23  7100.0  人事
4   钱七  22     NaN  财务
6  NaN  30  6700.0  人事

In [81]:
df = df.fillna(value={"年龄": 23})
df["年龄"] = df["年龄"].astype(int)
df

    姓名  年龄      工资  部门
0   张三  23  5000.0  财务
1   李四  45  8000.0  技术
2   王五  31  6200.0  技术
3   赵六  23  7100.0  人事
4   钱七  22     NaN  财务
6  NaN  30  6700.0  人事

In [63]:
gzsum= df["工资"].sum()
gzmean= df["工资"].mean()
gzstd= df["工资"].std()
df

   姓名    年龄      工资  部门
0  张三  23.0  5000.0  财务
1  李四  45.0  8000.0  技术
2  王五  31.0  6200.0  技术
3  赵六   NaN  7100.0  人事
4  钱七  22.0     NaN  财务

In [72]:
df.groupby("部门").agg(平均工资=("工资", "mean"),总人数=("姓名", "count"))

      平均工资  总人数
部门
人事  6900.0    1
技术  7100.0    2
财务  5000.0    2