In [29]:
import pandas as pd
import numpy as np
# df=pd.read_csv('pandas_exam_data.csv').head()
df=pd.read_csv('pandas_exam_data.csv')

In [30]:
pd.isnull(df)
df.dropna()

   姓名    年龄      工资  部门
0  张三  23.0  5000.0  财务
1  李四  45.0  8000.0  技术
2  王五  31.0  6200.0  技术
5  李四  45.0  8000.0  技术

In [31]:
df.fillna({"工资": df["工资"].mean()})

    姓名    年龄           工资  部门
0   张三  23.0  5000.000000  财务
1   李四  45.0  8000.000000  技术
2   王五  31.0  6200.000000  技术
3   赵六   NaN  7100.000000  人事
4   钱七  22.0  6833.333333  财务
5   李四  45.0  8000.000000  技术
6  NaN  30.0  6700.000000  人事

In [32]:
# df['是否重复'] = df.duplicated(keep=False)
df = df.drop_duplicates(subset=["姓名"])
df

    姓名    年龄      工资  部门
0   张三  23.0  5000.0  财务
1   李四  45.0  8000.0  技术
2   王五  31.0  6200.0  技术
3   赵六   NaN  7100.0  人事
4   钱七  22.0     NaN  财务
6  NaN  30.0  6700.0  人事

In [33]:
df = df.fillna(value={"年龄": 23})
df["年龄"] = df["年龄"].astype(int)
df

    姓名  年龄      工资  部门
0   张三  23  5000.0  财务
1   李四  45  8000.0  技术
2   王五  31  6200.0  技术
3   赵六  23  7100.0  人事
4   钱七  22     NaN  财务
6  NaN  30  6700.0  人事

In [34]:
gzsum= df["工资"].sum()
gzmean= df["工资"].mean()
gzstd= df["工资"].std()
print(gzsum,gzmean,gzstd)

33000.0 6600.0 1111.3055385446435

In [35]:
df.groupby("部门").agg(平均工资=("工资", "mean"),总人数=("姓名", "count"))

      平均工资  总人数
部门
人事  6900.0    1
技术  7100.0    2
财务  5000.0    2

In [36]:
df["年龄段"] = pd.cut(
    df["年龄"],
    bins=[0, 25, 35, 50],
    labels=["青年", "中年", "中老年"]
)
df

    姓名  年龄      工资  部门  年龄段
0   张三  23  5000.0  财务   青年
1   李四  45  8000.0  技术  中老年
2   王五  31  6200.0  技术   中年
3   赵六  23  7100.0  人事   青年
4   钱七  22     NaN  财务   青年
6  NaN  30  6700.0  人事   中年

In [38]:
df["部门"].value_counts()

部门
财务    2
技术    2
人事    2
Name: count, dtype: int64

In [39]:
df['收入登记']=np.where(df['工资']>=7000,'高收入','一般')
df

    姓名  年龄      工资  部门  年龄段 收入登记
0   张三  23  5000.0  财务   青年   一般
1   李四  45  8000.0  技术  中老年  高收入
2   王五  31  6200.0  技术   中年   一般
3   赵六  23  7100.0  人事   青年  高收入
4   钱七  22     NaN  财务   青年   一般
6  NaN  30  6700.0  人事   中年   一般

In [40]:
bt=df[df['工资'].between(6000, 8000, inclusive="both")]
bt

    姓名  年龄      工资  部门  年龄段 收入登记
1   李四  45  8000.0  技术  中老年  高收入
2   王五  31  6200.0  技术   中年   一般
3   赵六  23  7100.0  人事   青年  高收入
6  NaN  30  6700.0  人事   中年   一般

In [43]:
total= len(df['姓名'])
total

6

In [47]:
df.to_csv("processed_exam_data.csv", index=False)